"""new columns for statswith int

Revision ID: 65708dcc459c
Revises: f7c60e266bb9
Create Date: 2026-08-05 18:35:37.900848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65708dcc459c'
down_revision: Union[str, Sequence[str], None] = 'f7c60e266bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('strength', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('dexterity', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('constitution', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('intelligence', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('wisdom', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('charisma', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('strength_save', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('dexterity_save', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('constitution_save', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('intelligence_save', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('wisdom_save', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('charisma_save', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'charisma_save')
    op.drop_column('monsters', 'wisdom_save')
    op.drop_column('monsters', 'intelligence_save')
    op.drop_column('monsters', 'constitution_save')
    op.drop_column('monsters', 'dexterity_save')
    op.drop_column('monsters', 'strength_save')
    op.drop_column('monsters', 'charisma')
    op.drop_column('monsters', 'wisdom')
    op.drop_column('monsters', 'intelligence')
    op.drop_column('monsters', 'constitution')
    op.drop_column('monsters', 'dexterity')
    op.drop_column('monsters', 'strength')
    # ### end Alembic commands ###
