"""initial

Revision ID: bca9f31ae4b8
Revises: 
Create Date: 2026-08-05 15:01:13.660543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca9f31ae4b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('source', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('size', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('creature_type', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('alignment', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('info', sa.JSON(), nullable=True))
    op.add_column('monsters', sa.Column('abilities', sa.JSON(), nullable=True))
    op.add_column('monsters', sa.Column('stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'stats')
    op.drop_column('monsters', 'abilities')
    op.drop_column('monsters', 'info')
    op.drop_column('monsters', 'alignment')
    op.drop_column('monsters', 'creature_type')
    op.drop_column('monsters', 'size')
    op.drop_column('monsters', 'source')
    # ### end Alembic commands ###
