"""new columns

Revision ID: f7c60e266bb9
Revises: aca9f2d53e67
Create Date: 2026-08-05 18:10:16.473529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c60e266bb9'
down_revision: Union[str, Sequence[str], None] = 'aca9f2d53e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('armor_class', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('initiative', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('hp', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('movement', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('resistances', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('immunities', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('senses', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('areal', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('gear', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('loot', sa.String(), nullable=True))
    op.add_column('monsters', sa.Column('danger', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monsters', 'danger')
    op.drop_column('monsters', 'loot')
    op.drop_column('monsters', 'gear')
    op.drop_column('monsters', 'areal')
    op.drop_column('monsters', 'languages')
    op.drop_column('monsters', 'senses')
    op.drop_column('monsters', 'immunities')
    op.drop_column('monsters', 'resistances')
    op.drop_column('monsters', 'skills')
    op.drop_column('monsters', 'movement')
    op.drop_column('monsters', 'hp')
    op.drop_column('monsters', 'initiative')
    op.drop_column('monsters', 'armor_class')
    # ### end Alembic commands ###
