"""initial

Revision ID: 0db05f0c5ba7
Revises: 
Create Date: 2026-08-07 14:44:27.657433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db05f0c5ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.Column('combatants', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('creature_type', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hit_points_value', sa.Integer(), nullable=False),
    sa.Column('hit_points_formula', sa.String(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('damage_resistance', sa.String(), nullable=False),
    sa.Column('damage_immunity', sa.String(), nullable=False),
    sa.Column('damage_vulnerability', sa.String(), nullable=False),
    sa.Column('senses', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('challenge_rating', sa.String(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('treasure', sa.String(), nullable=False),
    sa.Column('habitat', sa.String(), nullable=False),
    sa.Column('strength_value', sa.Integer(), nullable=False),
    sa.Column('strength_mod', sa.Integer(), nullable=False),
    sa.Column('strength_save', sa.Integer(), nullable=False),
    sa.Column('dexterity_value', sa.Integer(), nullable=False),
    sa.Column('dexterity_mod', sa.Integer(), nullable=False),
    sa.Column('dexterity_save', sa.Integer(), nullable=False),
    sa.Column('constitution_value', sa.Integer(), nullable=False),
    sa.Column('constitution_mod', sa.Integer(), nullable=False),
    sa.Column('constitution_save', sa.Integer(), nullable=False),
    sa.Column('intelligence_value', sa.Integer(), nullable=False),
    sa.Column('intelligence_mod', sa.Integer(), nullable=False),
    sa.Column('intelligence_save', sa.Integer(), nullable=False),
    sa.Column('wisdom_value', sa.Integer(), nullable=False),
    sa.Column('wisdom_mod', sa.Integer(), nullable=False),
    sa.Column('wisdom_save', sa.Integer(), nullable=False),
    sa.Column('charisma_value', sa.Integer(), nullable=False),
    sa.Column('charisma_mod', sa.Integer(), nullable=False),
    sa.Column('charisma_save', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=True)
    op.create_table('monster_attacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('monster_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('attack_range', sa.String(), nullable=False),
    sa.Column('hit_bonus', sa.Integer(), nullable=False),
    sa.Column('reach', sa.String(), nullable=False),
    sa.Column('damage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster_attacks')
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_table('encounter')
    # ### end Alembic commands ###
