"""initial

Revision ID: ac2e6d49a48c
Revises: 
Create Date: 2026-08-25 19:30:46.731343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2e6d49a48c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('character_class', sa.Enum('ARTIFICER', 'BARD', 'BARBARIAN', 'FIGHTER', 'WIZARD', 'DRUID', 'CLERIC', 'WARLOCK', 'MONK', 'PALADIN', 'ROGUE', 'RANGER', 'SORCERER', name='characterclass'), nullable=False),
    sa.Column('race', sa.Enum('AASIMAR', 'GNOME', 'GOLIATH', 'DWARF', 'DRAGONBORN', 'ORC', 'HALFLING', 'TIEFLING', 'HUMAN', 'ELF', name='race'), nullable=False),
    sa.Column('alignment', sa.Enum('CHAOTIC_EVIL', 'CHAOTIC_NEUTRAL', 'CHAOTIC_GOOD', 'NEUTRAL_EVIL', 'NEUTRAL', 'NEUTRAL_GOOD', 'LAWFUL_EVIL', 'LAWFUL_NEUTRAL', 'LAWFUL_GOOD', name='creaturealignment'), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hit_points_value', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('senses', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('strength_value', sa.Integer(), nullable=False),
    sa.Column('is_strength_save', sa.Boolean(), nullable=False),
    sa.Column('dexterity_value', sa.Integer(), nullable=False),
    sa.Column('is_dexterity_save', sa.Boolean(), nullable=False),
    sa.Column('constitution_value', sa.Integer(), nullable=False),
    sa.Column('is_constitution_save', sa.Boolean(), nullable=False),
    sa.Column('intelligence_value', sa.Integer(), nullable=False),
    sa.Column('is_intelligence_save', sa.Boolean(), nullable=False),
    sa.Column('wisdom_value', sa.Integer(), nullable=False),
    sa.Column('is_wisdom_save', sa.Boolean(), nullable=False),
    sa.Column('charisma_value', sa.Integer(), nullable=False),
    sa.Column('is_charisma_save', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('character_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('encounters',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('encounter_id')
    )
    op.create_table('monsters',
    sa.Column('monster_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('ADV_IN_FAERUN', 'BOOK_OF_HUNGERS', 'CUSTOM', 'LORWYN', 'MM_2024', 'NETHERIL', 'PHB_2024', 'RAVENLOFT', name='monstersource'), nullable=False),
    sa.Column('size', sa.Enum('TINY', 'SMALL', 'AVG', 'BIG', 'HUGE', 'GIANT', name='monstersize'), nullable=False),
    sa.Column('creature_type', sa.Enum('ABERRATION', 'BEAST', 'CELESTIAL', 'CONSTRUCT', 'DRAGON', 'ELEMENTAL', 'FEY', 'FIEND', 'GIANT', 'HUMANOID', 'MONSTROSITY', 'OOZE', 'PLANT', 'UNDEAD', name='monstertype'), nullable=False),
    sa.Column('hit_points_formula', sa.String(), nullable=False),
    sa.Column('challenge_rating', sa.String(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('treasure', sa.String(), nullable=False),
    sa.Column('habitat', sa.String(), nullable=False),
    sa.Column('alignment', sa.Enum('CHAOTIC_EVIL', 'CHAOTIC_NEUTRAL', 'CHAOTIC_GOOD', 'NEUTRAL_EVIL', 'NEUTRAL', 'NEUTRAL_GOOD', 'LAWFUL_EVIL', 'LAWFUL_NEUTRAL', 'LAWFUL_GOOD', name='creaturealignment'), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hit_points_value', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('senses', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('strength_value', sa.Integer(), nullable=False),
    sa.Column('is_strength_save', sa.Boolean(), nullable=False),
    sa.Column('dexterity_value', sa.Integer(), nullable=False),
    sa.Column('is_dexterity_save', sa.Boolean(), nullable=False),
    sa.Column('constitution_value', sa.Integer(), nullable=False),
    sa.Column('is_constitution_save', sa.Boolean(), nullable=False),
    sa.Column('intelligence_value', sa.Integer(), nullable=False),
    sa.Column('is_intelligence_save', sa.Boolean(), nullable=False),
    sa.Column('wisdom_value', sa.Integer(), nullable=False),
    sa.Column('is_wisdom_save', sa.Boolean(), nullable=False),
    sa.Column('charisma_value', sa.Integer(), nullable=False),
    sa.Column('is_charisma_save', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('monster_id')
    )
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=True)
    op.create_table('actions',
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('ACTION', 'BONUS_ACTION', 'REACTION', 'LEGENDARY_ACTION', 'FEATURE', name='actiontype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('range', sa.String(), nullable=False),
    sa.Column('reach', sa.String(), nullable=False),
    sa.Column('hit_bonus', sa.Integer(), nullable=False),
    sa.Column('damage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_action_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('combatants',
    sa.Column('combatant_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('current_initiative', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'UNCONSCIOUS', name='combatantstatus'), nullable=False),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_combatant_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('combatant_id')
    )
    op.create_table('damage_resistances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('resistance', sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_resistance_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_vulnerabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('vulnerability', sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_vulnerability_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immunities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('immunity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_immunity_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immunities')
    op.drop_table('damage_vulnerabilities')
    op.drop_table('damage_resistances')
    op.drop_table('combatants')
    op.drop_table('actions')
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_table('encounters')
    op.drop_table('characters')
    # ### end Alembic commands ###
