"""characters-table-and-character-attack-and-nullableFK-in-combatants

Revision ID: ac2ed8412b74
Revises: 86f59c1c98f5
Create Date: 2026-08-20 15:11:46.929582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2ed8412b74'
down_revision: Union[str, Sequence[str], None] = '86f59c1c98f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('character_class', sa.Enum('ARTIFICER', 'BARD', 'BARBARIAN', 'FIGHTER', 'WIZARD', 'DRUID', 'CLERIC', 'WARLOCK', 'MONK', 'PALADIN', 'ROGUE', 'RANGER', 'SORCERER', name='characterclass'), nullable=False),
    sa.Column('race', sa.Enum('AASIMAR', 'GNOME', 'GOLIATH', 'DWARF', 'DRAGONBORN', 'ORC', 'HALFLING', 'TIEFLING', 'HUMAN', 'ELF', name='race'), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('hit_points_value', sa.Integer(), nullable=False),
    sa.Column('damage_resistance', sa.String(), nullable=False),
    sa.Column('damage_immunity', sa.String(), nullable=False),
    sa.Column('damage_vulnerability', sa.String(), nullable=False),
    sa.Column('strength_value', sa.Integer(), nullable=False),
    sa.Column('strength_mod', sa.Integer(), nullable=False),
    sa.Column('strength_save', sa.Integer(), nullable=False),
    sa.Column('dexterity_value', sa.Integer(), nullable=False),
    sa.Column('dexterity_mod', sa.Integer(), nullable=False),
    sa.Column('dexterity_save', sa.Integer(), nullable=False),
    sa.Column('constitution_value', sa.Integer(), nullable=False),
    sa.Column('constitution_mod', sa.Integer(), nullable=False),
    sa.Column('constitution_save', sa.Integer(), nullable=False),
    sa.Column('intelligence_value', sa.Integer(), nullable=False),
    sa.Column('intelligence_mod', sa.Integer(), nullable=False),
    sa.Column('intelligence_save', sa.Integer(), nullable=False),
    sa.Column('wisdom_value', sa.Integer(), nullable=False),
    sa.Column('wisdom_mod', sa.Integer(), nullable=False),
    sa.Column('wisdom_save', sa.Integer(), nullable=False),
    sa.Column('charisma_value', sa.Integer(), nullable=False),
    sa.Column('charisma_mod', sa.Integer(), nullable=False),
    sa.Column('charisma_save', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('character_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character_attacks',
    sa.Column('attack_id', sa.String(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('attack_range', sa.String(), nullable=False),
    sa.Column('hit_bonus', sa.Integer(), nullable=False),
    sa.Column('reach', sa.String(), nullable=False),
    sa.Column('damage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['character_name'], ['characters.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attack_id')
    )
    op.alter_column('combatants', 'monster_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('combatants', 'monster_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('character_attacks')
    op.drop_table('characters')
    # ### end Alembic commands ###
