"""initial

Revision ID: 441f8848db4c
Revises: 
Create Date: 2026-08-11 19:18:12.587257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441f8848db4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('encounter_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('encounter_id')
    )
    op.create_table('monsters',
    sa.Column('monster_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('ADV_IN_FAERUN', 'BOOK_OF_HUNGERS', 'CUSTOM', 'LORWYN', 'MM_2024', 'NETHERIL', 'PHB_2024', 'RAVENLOFT', name='monstersource'), nullable=False),
    sa.Column('size', sa.Enum('TINY', 'SMALL', 'AVG', 'BIG', 'HUGE', 'GIANT', name='monstersize'), nullable=False),
    sa.Column('creature_type', sa.Enum('ABERRATION', 'BEAST', 'CELESTIAL', 'CONSTRUCT', 'DRAGON', 'ELEMENTAL', 'FEY', 'FIEND', 'GIANT', 'HUMANOID', 'MONSTROSITY', 'OOZE', 'PLANT', 'UNDEAD', name='monstertype'), nullable=False),
    sa.Column('alignment', sa.Enum('CHAOTIC_EVIL', 'CHAOTIC_NEUTRAL', 'CHAOTIC_GOOD', 'NEUTRAL_EVIL', 'NEUTRAL', 'NEUTRAL_GOOD', 'LAWFUL_EVIL', 'LAWFUL_NEUTRAL', 'LAWFUL_GOOD', name='monsteralignment'), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hit_points_value', sa.Integer(), nullable=False),
    sa.Column('hit_points_formula', sa.String(), nullable=False),
    sa.Column('speed', sa.String(), nullable=False),
    sa.Column('skills', sa.String(), nullable=False),
    sa.Column('damage_resistance', sa.String(), nullable=False),
    sa.Column('damage_immunity', sa.String(), nullable=False),
    sa.Column('damage_vulnerability', sa.String(), nullable=False),
    sa.Column('senses', sa.String(), nullable=False),
    sa.Column('languages', sa.String(), nullable=False),
    sa.Column('challenge_rating', sa.String(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('treasure', sa.String(), nullable=False),
    sa.Column('habitat', sa.String(), nullable=False),
    sa.Column('strength_value', sa.Integer(), nullable=False),
    sa.Column('strength_mod', sa.Integer(), nullable=False),
    sa.Column('strength_save', sa.Integer(), nullable=False),
    sa.Column('dexterity_value', sa.Integer(), nullable=False),
    sa.Column('dexterity_mod', sa.Integer(), nullable=False),
    sa.Column('dexterity_save', sa.Integer(), nullable=False),
    sa.Column('constitution_value', sa.Integer(), nullable=False),
    sa.Column('constitution_mod', sa.Integer(), nullable=False),
    sa.Column('constitution_save', sa.Integer(), nullable=False),
    sa.Column('intelligence_value', sa.Integer(), nullable=False),
    sa.Column('intelligence_mod', sa.Integer(), nullable=False),
    sa.Column('intelligence_save', sa.Integer(), nullable=False),
    sa.Column('wisdom_value', sa.Integer(), nullable=False),
    sa.Column('wisdom_mod', sa.Integer(), nullable=False),
    sa.Column('wisdom_save', sa.Integer(), nullable=False),
    sa.Column('charisma_value', sa.Integer(), nullable=False),
    sa.Column('charisma_mod', sa.Integer(), nullable=False),
    sa.Column('charisma_save', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('monster_id')
    )
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=True)
    op.create_table('combatants',
    sa.Column('combatant_id', sa.String(), nullable=False),
    sa.Column('encounter_id', sa.String(), nullable=False),
    sa.Column('monster_id', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'UNCONSCIOUS', name='combatantstatus'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.encounter_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.monster_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('combatant_id')
    )
    op.create_table('monster_attacks',
    sa.Column('attack_id', sa.String(), nullable=False),
    sa.Column('monster_name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('attack_range', sa.String(), nullable=False),
    sa.Column('hit_bonus', sa.Integer(), nullable=False),
    sa.Column('reach', sa.String(), nullable=False),
    sa.Column('damage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['monster_name'], ['monsters.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attack_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster_attacks')
    op.drop_table('combatants')
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_table('encounter')
    # ### end Alembic commands ###
