"""doubleFK-in-combatants

Revision ID: 7703bdb5745e
Revises: ac2ed8412b74
Create Date: 2026-08-20 15:13:51.265950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7703bdb5745e'
down_revision: Union[str, Sequence[str], None] = 'ac2ed8412b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combatants', sa.Column('character_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'combatants', 'characters', ['character_id'], ['character_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_check_constraint('ck_combatant_exactly_one_owner', 'combatants', '\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_combatant_exactly_one_owner', 'combatants', type_='check')
    op.drop_constraint(None, 'combatants', type_='foreignkey')
    op.drop_column('combatants', 'character_id')
    # ### end Alembic commands ###
