"""initial

Revision ID: 9533e150bb56
Revises: 
Create Date: 2026-09-09 17:05:23.141340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9533e150bb56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('character_class', sa.Enum('ARTIFICER', 'BARD', 'BARBARIAN', 'FIGHTER', 'WIZARD', 'DRUID', 'CLERIC', 'WARLOCK', 'MONK', 'PALADIN', 'ROGUE', 'RANGER', 'SORCERER', name='characterclass', native_enum=False), nullable=False),
    sa.Column('race', sa.Enum('AASIMAR', 'GNOME', 'GOLIATH', 'DWARF', 'DRAGONBORN', 'ORC', 'HALFLING', 'TIEFLING', 'HUMAN', 'ELF', name='race', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('hit_points_formula', sa.String(), nullable=False),
    sa.Column('speed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resistances', postgresql.ARRAY(sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype', native_enum=False)), nullable=False),
    sa.Column('immunities', postgresql.ARRAY(sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype', native_enum=False)), nullable=False),
    sa.Column('vulnerabilities', postgresql.ARRAY(sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype', native_enum=False)), nullable=False),
    sa.Column('condition_immunities', postgresql.ARRAY(sa.Enum('UNCONSCIOUS', 'FRIGHTENED', 'EXHAUSTION', 'INVISIBLE', 'INCAPACITATED', 'DEAFENED', 'PETRIFIED', 'PRONE', 'RESTRAINED', 'BLINDED', 'POISONED', 'CHARMED', 'STUNNED', 'PARALYZED', 'GRAPPLED', name='conditiontype', native_enum=False)), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('saves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alignment', sa.Enum('CHAOTIC_EVIL', 'CHAOTIC_NEUTRAL', 'CHAOTIC_GOOD', 'NEUTRAL_EVIL', 'NEUTRAL', 'NEUTRAL_GOOD', 'LAWFUL_EVIL', 'LAWFUL_NEUTRAL', 'LAWFUL_GOOD', name='creaturealignment', native_enum=False), nullable=False),
    sa.Column('size', sa.Enum('TINY', 'SMALL', 'AVG', 'BIG', 'HUGE', 'GIANT', name='creaturesize', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('CUSTOM', 'DMG', 'ADV_IN_FAERUN', 'BOOK_OF_HUNGERS', 'LORWYN', 'MM', 'NETHERIL', 'PHB', 'RAVENLOFT', name='creaturesource', native_enum=False), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('senses', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    op.create_table('encounters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('type', sa.Enum('ABERRATION', 'BEAST', 'CELESTIAL', 'CONSTRUCT', 'DRAGON', 'ELEMENTAL', 'FEY', 'FIEND', 'GIANT', 'HUMANOID', 'MONSTROSITY', 'OOZE', 'PLANT', 'UNDEAD', name='monstertype', native_enum=False), nullable=False),
    sa.Column('challenge_rating', sa.String(), nullable=False),
    sa.Column('equipment', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('treasure', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('environment', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('initiative', sa.Integer(), nullable=False),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('hit_points_formula', sa.String(), nullable=False),
    sa.Column('speed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resistances', postgresql.ARRAY(sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype', native_enum=False)), nullable=False),
    sa.Column('immunities', postgresql.ARRAY(sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype', native_enum=False)), nullable=False),
    sa.Column('vulnerabilities', postgresql.ARRAY(sa.Enum('BLUDGEONING', 'PIERCING', 'SLASHING', 'ACID', 'COLD', 'FIRE', 'FORCE', 'LIGHTNING', 'NECROTIC', 'POISON', 'PSYCHIC', 'RADIANT', 'THUNDER', name='damagetype', native_enum=False)), nullable=False),
    sa.Column('condition_immunities', postgresql.ARRAY(sa.Enum('UNCONSCIOUS', 'FRIGHTENED', 'EXHAUSTION', 'INVISIBLE', 'INCAPACITATED', 'DEAFENED', 'PETRIFIED', 'PRONE', 'RESTRAINED', 'BLINDED', 'POISONED', 'CHARMED', 'STUNNED', 'PARALYZED', 'GRAPPLED', name='conditiontype', native_enum=False)), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('dexterity', sa.Integer(), nullable=False),
    sa.Column('constitution', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('wisdom', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Integer(), nullable=False),
    sa.Column('saves', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alignment', sa.Enum('CHAOTIC_EVIL', 'CHAOTIC_NEUTRAL', 'CHAOTIC_GOOD', 'NEUTRAL_EVIL', 'NEUTRAL', 'NEUTRAL_GOOD', 'LAWFUL_EVIL', 'LAWFUL_NEUTRAL', 'LAWFUL_GOOD', name='creaturealignment', native_enum=False), nullable=False),
    sa.Column('size', sa.Enum('TINY', 'SMALL', 'AVG', 'BIG', 'HUGE', 'GIANT', name='creaturesize', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('CUSTOM', 'DMG', 'ADV_IN_FAERUN', 'BOOK_OF_HUNGERS', 'LORWYN', 'MM', 'NETHERIL', 'PHB', 'RAVENLOFT', name='creaturesource', native_enum=False), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('senses', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monsters_name'), 'monsters', ['name'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('ACTION', 'BONUS_ACTION', 'REACTION', 'SPELLCASTING', 'LEGENDARY_ACTION', 'TRAIT', name='abilitytype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('distance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_method', sa.Enum('ROLL', 'SAVE', 'ROLL_THEN_SAVE', 'AUTO', name='hitmethod', native_enum=False), nullable=False),
    sa.Column('hit_bonus', sa.Integer(), nullable=True),
    sa.Column('dc', sa.Integer(), nullable=True),
    sa.Column('on_successful_save', postgresql.ARRAY(sa.Enum('HALF_DMG', 'NO_DMG', 'NO_CONDITION', name='saveeffect', native_enum=False)), nullable=True),
    sa.Column('damage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condition', postgresql.ARRAY(sa.Enum('UNCONSCIOUS', 'FRIGHTENED', 'EXHAUSTION', 'INVISIBLE', 'INCAPACITATED', 'DEAFENED', 'PETRIFIED', 'PRONE', 'RESTRAINED', 'BLINDED', 'POISONED', 'CHARMED', 'STUNNED', 'PARALYZED', 'GRAPPLED', name='conditiontype', native_enum=False)), nullable=True),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_action_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combatants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('monster_id', sa.Uuid(), nullable=True),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('current_hp', sa.Integer(), nullable=False),
    sa.Column('current_initiative', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'UNCONSCIOUS', name='combatantstatus', native_enum=False), nullable=False),
    sa.CheckConstraint('\n            (monster_id IS NOT NULL AND character_id IS NULL)\n            OR\n            (monster_id IS NULL AND character_id IS NOT NULL)\n            ', name='ck_combatant_exactly_one_owner'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combatants')
    op.drop_table('actions')
    op.drop_index(op.f('ix_monsters_name'), table_name='monsters')
    op.drop_table('monsters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
