"""combataant-current-initiative

Revision ID: 86f59c1c98f5
Revises: 441f8848db4c
Create Date: 2026-08-17 21:44:58.338578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f59c1c98f5'
down_revision: Union[str, Sequence[str], None] = '441f8848db4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combatants', sa.Column('current_initiative', sa.Integer(), nullable=False, server_default="0",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('combatants', 'current_initiative')
    # ### end Alembic commands ###
