"""not unique names

Revision ID: aca9f2d53e67
Revises: bca9f31ae4b8
Create Date: 2026-08-05 18:02:51.393607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca9f2d53e67'
down_revision: Union[str, Sequence[str], None] = 'bca9f31ae4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('monsters_name_key'), 'monsters', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('monsters_name_key'), 'monsters', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
