"""update cascade for attacks

Revision ID: bddb5b58d768
Revises: 00826354b2b4
Create Date: 2026-08-07 15:49:18.386491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bddb5b58d768'
down_revision: Union[str, Sequence[str], None] = '00826354b2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('monster_attacks_monster_name_fkey'), 'monster_attacks', type_='foreignkey')
    op.create_foreign_key(None, 'monster_attacks', 'monsters', ['monster_name'], ['name'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monster_attacks', type_='foreignkey')
    op.create_foreign_key(op.f('monster_attacks_monster_name_fkey'), 'monster_attacks', 'monsters', ['monster_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###
