"""initial

Revision ID: e67e8ff968b8
Revises: 
Create Date: 2026-08-06 20:10:36.456727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67e8ff968b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.Column('combatants', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monsters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('creature_type', sa.String(), nullable=True),
    sa.Column('alignment', sa.String(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('armor_class', sa.String(), nullable=True),
    sa.Column('initiative', sa.String(), nullable=True),
    sa.Column('hp', sa.String(), nullable=True),
    sa.Column('movement', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('resistances', sa.String(), nullable=True),
    sa.Column('immunities', sa.String(), nullable=True),
    sa.Column('senses', sa.String(), nullable=True),
    sa.Column('languages', sa.String(), nullable=True),
    sa.Column('areal', sa.String(), nullable=True),
    sa.Column('gear', sa.String(), nullable=True),
    sa.Column('loot', sa.String(), nullable=True),
    sa.Column('danger', sa.String(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('strength_save', sa.String(), nullable=True),
    sa.Column('dexterity_save', sa.String(), nullable=True),
    sa.Column('constitution_save', sa.String(), nullable=True),
    sa.Column('intelligence_save', sa.String(), nullable=True),
    sa.Column('wisdom_save', sa.String(), nullable=True),
    sa.Column('charisma_save', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monsters')
    op.drop_table('encounter')
    # ### end Alembic commands ###
